# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install necessary packages
RUN apk add --no-cache bash gcc musl-dev

WORKDIR /app

# Copy all files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir mcp httpx

# Fix the Volatility directory path in the server script so it uses the local volatility3 folder
RUN sed -i 's|C:\\Users\\visha\\Desktop\\volatility3|/app/volatility3|' volatility_mcp_server.py

CMD ["python", "volatility_mcp_server.py"]
